language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  # @todo #12 Интегрировать test в setup.py
  - coverage run setup.py check
after_success:
  - codecov
